apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-redis
  name: {{ .Values.redis.name }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: db-redis
    spec:
      containers:
      - image: {{ .Values.redis.image.repo }}
        name: {{ .Values.redis.name }}
        resources: {}
      restartPolicy: Always
status: {}
