apiVersion: v1
kind: Service
metadata:
  name: {{ include "helix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helix.labels" . | nindent 4 }}
    component: helix
spec:
  type: {{ .Values.helix.service.type }}
  ports:
    - port: {{ .Values.helix.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helix.selectorLabels" . | nindent 4 }}
    component: helix
