# Docker Compose for deployment. This removes the hard coded usernames and
# passwords and pulls Docker Hub seedplatform/seed for the latest version.
# It is recommended that you use docker stack to deploy which defaults to using
# the docker-compose.local.yml file. This file is intended to support simple
# production-based docker-compose deployments (not docker stack).
# Must set the following environment variables.
#   POSTGRES_USER
#   POSTGRES_PASSWORD
#   SEED_ADMIN_USER
#   SEED_ADMIN_PASSWORD
#   SEED_ADMIN_ORG
#   SECRET_KEY

version: '3'
services:
  db-postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_DB=seed
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - seed_pgdata:/var/lib/postgresql/data
  db-redis:
    image: redis:5.0.1
  web:
    image: seedplatform/seed
    environment:
      - POSTGRES_DB=seed
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SEED_ADMIN_USER
      - SEED_ADMIN_PASSWORD
      - SEED_ADMIN_ORG
      - SECRET_KEY
      - DJANGO_SETTINGS_MODULE=config.settings.docker
    depends_on:
      - db-redis
      - db-postgres
    volumes:
      - seed_media:/seed/media
    ports:
      - "80:80"
  web-celery:
    command: /seed/docker/start_celery_docker.sh
    image: seedplatform/seed
    environment:
      - POSTGRES_DB=seed
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - NUMBER_OF_WORKERS
    depends_on:
      - db-redis
      - db-postgres
      - web
    volumes:
      - seed_media:/seed/media
  oep-city-1:
    # This is a placeholder. If needed, follow the instructions to enable: https://cloud.docker.com/u/seedplatform/repository/docker/seedplatform/oep
    image: seedplatform/oep:1.0.0-SNAPSHOT
    environment:
      - OEP_DISABLED=true
volumes:
  seed_pgdata:
    external: true
  seed_media:
    external: true
