# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-06 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0114_auto_20191202_1652'),
        ('seed', '0115_backfill_organization_columns'),
    ]

    operations = [
    ]
