# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-03 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0115_backfill_organization_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenassessmentpropertyauditlog',
            name='record_type',
            field=models.IntegerField(blank=True, choices=[(0, 'ImportFile'), (1, 'UserEdit'), (2, 'UserCreate'), (3, 'UserExport')], null=True),
        ),
        migrations.AlterField(
            model_name='propertyauditlog',
            name='record_type',
            field=models.IntegerField(blank=True, choices=[(0, 'ImportFile'), (1, 'UserEdit'), (2, 'UserCreate'), (3, 'UserExport')], null=True),
        ),
        migrations.AlterField(
            model_name='taxlotauditlog',
            name='record_type',
            field=models.IntegerField(blank=True, choices=[(0, 'ImportFile'), (1, 'UserEdit'), (2, 'UserCreate'), (3, 'UserExport')], null=True),
        ),
    ]
