# Generated by Django 2.2.10 on 2020-04-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0116_merge_20191206_0250'),
        ('seed', '0122_auto_20200303_1428'),
    ]

    operations = [
    ]
