# Generated by Django 2.2.10 on 2020-05-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0124_auto_20200323_1509'),
        ('seed', '0123_merge_20200410_1509'),
    ]

    operations = [
    ]
