apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: default
spec:
  type: LoadBalancer
#  loadBalancerIP: 104.198.109.46
  externalTrafficPolicy: Local
  selector:
    io.kompose.service: nginx-ingress
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
    - name: kibana-http
      protocol: TCP
      port: 5601
  loadBalancerSourceRanges:
    - 0.0.0.0/0
