apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-ingress
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: nginx-ingress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-ingress
    spec:
      containers:
      - image: nginx:1.17.8
        imagePullPolicy: IfNotPresent
        name: nginx-ingress
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/seed-dev.conf
          name: nginx-ingress
          subPath: seed-dev.conf
        - mountPath: /etc/nginx/conf.d/kibana.conf
          name: nginx-ingress
          subPath: kibana.conf
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-ingress
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-ingress
        name: nginx-ingress
status: {}
