name: AWS Docker deployment

on:
  push:
    branches:
      - "develop"
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=sha,enable=true,priority=100,format=short
          images: ${{ steps.login-ecr.outputs.registry }}/helix

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H-%M')" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: >
            ${{ steps.meta.outputs.tags }},
            ${{ steps.login-ecr.outputs.registry }}/helix:${{ steps.date.outputs.date }},
            ${{ steps.login-ecr.outputs.registry }}/helix:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/helix:latest
          cache-to: type=inline

      - name: Trigger Ansible Image update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Replace image tag
          repo: ClearlyEnergy/helix-aws-config
          token: ${{ secrets.ANSIBLE_ACCESS_TOKEN }}
          ref: master
          inputs: '{ "image": "${{ steps.login-ecr.outputs.registry }}/helix:${{ steps.date.outputs.date }}", "role": "helix", "host": "helix_staging", "path": "ansible/group_vars/helix_staging/vars.yml" }'

      - name: Trigger Kubernetes Deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy staging image
          repo: ClearlyEnergy/helix-aws-config
          token: ${{ secrets.ANSIBLE_ACCESS_TOKEN }}
          ref: master
          inputs: '{ "image": "${{ steps.login-ecr.outputs.registry }}/helix:${{ steps.date.outputs.date }}", "role": "helix", "host": "helix_staging", "path": "ansible/group_vars/helix_staging/vars.yml" }'
