name: AWS Docker deployment

on:
  push:
    branches:
      - "develop"
    paths-ignore:
      - "charts/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    uses: ClearlyEnergy/.github/.github/workflows/reusable-docker-release.yml@main
    with:
      image-name: "helix"
      use-cache: ${{ github.event_name == 'push' }}

  deploy:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.CE_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.CE_AUTOMATION_PRIVATE_KEY }}
          repositories: "${{ github.event.repository.name }},application-configuration"

      - name: Trigger Kubernetes deploy
        uses: actions/github-script@v8
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ClearlyEnergy',
              repo: 'application-configuration',
              workflow_id: 'update-kubernetes-staging-image.yml',
              ref: 'main',
              inputs: {
                image: "${{ needs.build-and-push.outputs.published-image }}",
                role: "helix",
              }
            });
